# Force OS X.
language: objective-c
matrix:
  include:
    - env: OSX=10.12
      os: osx
      osx_image: beta-xcode9.1
      rvm: system
    - env: OSX=10.11
      os: osx
      osx_image: xcode8.2.1
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.2.1
      rvm: system

before_install:
  - export TRAVIS_COMMIT=$(git rev-parse --verify -q HEAD)
  - cd /usr/local
  - sudo rm -rf /usr/local/.git/refs /usr/local/.git/packed-refs
  - sudo rsync -az "$TRAVIS_BUILD_DIR/" /usr/local/
  - sudo chown -R $USER /usr/local
  - export TRAVIS_BUILD_DIR="/usr/local"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - git reset --hard $TRAVIS_COMMIT
  - git clean -qxdff
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY/Library/Taps";
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
      git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot;
    else
      umask 022;
      git fetch --unshallow;
      export PATH="$PWD/bin:$PATH";
      HOMEBREW_CORE_TAP_DIR="$(brew --repo "homebrew/core")";
      mkdir -p "$HOMEBREW_CORE_TAP_DIR";
      git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot;
      HOMEBREW_TEST_BOT_TAP_DIR="$(brew --repo "homebrew/test-bot")";
      ln -s "$HOMEBREW_TEST_BOT_TAP_DIR/.git" "$HOMEBREW_TEST_BOT_TAP_DIR/Formula" "$HOMEBREW_CORE_TAP_DIR";
    fi

install:
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
